name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  clojars:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Build
        uses: ./.github/actions/setup-build
      - name: Set version
        run: |
          lein change version set '"${{github.event.release.tag_name}}"'
      - name: Release
        run: lein with-profile release deploy clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}

  maven:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Build
        uses: ./.github/actions/setup-build
      - name: Set version
        run: |
          lein change version set '"${{github.event.release.tag_name}}"'
      - name: Release
        run: lein with-profile release deploy maven
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
